'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LangCode = 'ms' | 'en' | 'zh' | 'ta' | 'ar';

export const LANGUAGES: { code: LangCode; label: string; flag: string }[] = [
  { code: 'ms', label: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'ta', label: 'தமிழ்', flag: '🇮🇳' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
];

const translations: Record<LangCode, Record<string, string>> = {
  ms: {
    // Settings
    'settings.title': 'Tetapan & Aksesibiliti',
    'settings.subtitle': 'Ubah suai pengalaman NADI anda',
    'settings.appearance': 'Penampilan',
    'settings.theme': 'Mod Tema',
    'settings.accessibility': 'Aksesibiliti',
    'settings.scale': 'Skala Antara Muka',
    'settings.scale_s': 'Standard',
    'settings.scale_m': 'Besar',
    'settings.scale_l': 'Terbesar',
    'settings.dyslexia': 'Fon Disleksia',
    'settings.dyslexia_desc': 'Meningkatkan kebolehbacaan dan jarak teks',
    'settings.contrast': 'Kontras Tinggi',
    'settings.contrast_desc': 'Memaksimumkan kontras visual elemen',
    'settings.motion': 'Kurangkan Pergerakan',
    'settings.motion_desc': 'Membatalkan animasi dan transisi UI',
    'settings.colorblind': 'Penapis Buta Warna',
    'settings.colorblind_desc': 'Ubah warna UI untuk masalah penglihatan warna',
    'settings.cb_none': 'Warna Asal',
    'settings.tutorial': 'Ulangi Tutorial',
    // Sivik
    'sivik.pass_title': 'Nadi-Pass',
    'sivik.pass_desc': 'Dompet sivik & reputasi',
    'sivik.pts_title': 'Mata Sivik',
    'sivik.pts_desc': 'Kumpul mata melalui laporan sivik, sukarelawan & penyertaan komuniti',
    'sivik.trust': 'Kepercayaan',
    'sivik.quests': 'Misi',
    'sivik.badges': 'Lencana',
    'sivik.crs_title': 'Skor Reputasi Sivik',
    'sivik.tab_ledger': 'Lejar Aktiviti',
    'sivik.tab_board': 'Papan Pendahulu',
    'sivik.board_title': 'Papan Pendahulu Komuniti',
    'sivik.export_csv': 'Eksport CSV',
    'sivik.no_activity': 'Tiada aktiviti lagi — mula melapor untuk kumpul mata!',
    // Bantuan
    'bantuan.title': 'Bantuan',
    'bantuan.desc': 'Bantuan & Sukarelawan',
    'bantuan.active_aid': 'Bantuan Aktif',
    'bantuan.volunteer': 'Sukarelawan',
    'bantuan.open_spots': 'Kekosongan',
    'bantuan.tab_aid': 'Program Bantuan',
    'bantuan.tab_vol': 'Sukarelawan',
    'bantuan.search_aid': 'Cari program bantuan...',
    'bantuan.no_aid': 'Tiada program bantuan dijumpai untuk kawasan anda',
    'bantuan.ai_title': 'Semak Kelayakan AI',
    'bantuan.ai_desc': 'Biar NADI AI semak program mana yang anda layak mohon.',
    'bantuan.ai_btn': 'Semak Sekarang',
    'bantuan.profile': 'Profil Pemohon',
    'bantuan.age': 'Umur',
    'bantuan.income': 'Pendapatan (RM)',
    'bantuan.status': 'Status',
    'bantuan.dependents': 'Tanggungan',
    'bantuan.status_work': 'Bekerja',
    'bantuan.status_nowork': 'Tidak Bekerja',
    'bantuan.status_student': 'Pelajar',
    'bantuan.status_retiree': 'Pesara',
    'bantuan.run_ai': 'Jalankan Analisis AI',
    'bantuan.analyzing': 'Menganalisis...',
    'bantuan.eligible': 'Layak',
    'bantuan.not_eligible': 'Tidak Layak',
    'bantuan.maybe_eligible': 'Mungkin Layak',
    'bantuan.provider': 'Penyedia:',
    'bantuan.visit_site': 'Layari Laman →',
    'vol.urgent_sos': '🚨 SOS Tempatan Segera',
    'vol.no_sos': 'Tiada permintaan SOS tempatan',
    'vol.nationwide': '🤝 Kempen Seluruh Negara 🇲🇾',
    'vol.refresh': '↻ Segar Semula',
    'vol.search': 'Cari mengikut organisasi, lokasi, atau peranan...',
    'vol.cat_all': 'Semua',
    'vol.cat_disaster': '🆘 Bencana',
    'vol.cat_edu': '📚 Pendidikan',
    'vol.cat_env': '🌿 Alam Sekitar',
    'vol.cat_health': '🏥 Kesihatan',
    'vol.cat_comm': '🤝 Komuniti',
    'vol.cat_elderly': '👵 Warga Emas',
    'vol.cat_youth': '⚡ Belia',
    'vol.finding': 'Sedang mencari peluang sukarelawan...',
    'vol.no_match': 'Tiada peluang yang sepadan',
    'vol.try_diff': 'Cuba carian atau kategori lain',
    'vol.signup': 'Daftar →',
    'vol.spots': 'tempat',
    'vol.browse': '🔗 Layari Terus',
    'vol.visit_portals': 'Lawati portal sukarelawan rasmi ini untuk mencari dan mendaftar aktiviti spesifik:',
    // Tour
    'tour.skip': 'Langkau',
    'tour.next': 'Seterusnya',
    'tour.finish': 'Mula 🚀',
    'tour.welcome_title': 'Selamat Datang ke NADI 🇲🇾',
    'tour.welcome_desc': 'Sistem operasi sivik anda. Mari lihat ciri-ciri utama.',
    'tour.bantuan_title': 'Bantuan & Sukarelawan',
    'tour.bantuan_desc': 'Cari program bantuan kerajaan dan sertai NGO seperti Mercy Malaysia.',
    'tour.dashboard_title': 'Hab Utama',
    'tour.dashboard_desc': 'Pusat maklumat, cuaca, misi dan impak sivik anda.',
    'tour.bencana_title': 'Pusat Bencana',
    'tour.bencana_desc': 'Dapatkan amaran bencana masa nyata dan pusat pemindahan di sekitar anda.',
    'tour.suara_title': 'Suara & Aduan',
    'tour.suara_desc': 'Aduan isu sivik. AI kami faham loghat Kelantan, Sarawak & lain-lain.',
    'tour.infra_title': 'Infra & Bencana',
    'tour.infra_desc': 'Kesan jalan berlubang dan pantau status banjir secara langsung.',
    'tour.heatmap_title': 'Peta Panas (Heatmap)',
    'tour.heatmap_desc': 'Lihat kepadatan aduan dan zon merah di sekitar anda.',
    'tour.community_title': 'Komuniti',
    'tour.community_desc': 'Sertai perbincangan sivik dan lihat aktiviti terbaru komuniti.',
    'tour.notif_title': 'Pemberitahuan',
    'tour.notif_desc': 'Terima kemas kini tentang aduan dan status banjir anda.',
    'tour.settings_title': 'Tetapan & Aksesibiliti',
    'tour.settings_desc': 'Tukar bahasa, mod buta warna, fon disleksia dan tema di sini.',
    // Header
    'greeting.morning': 'Selamat Pagi! ☀️',
    'greeting.noon': 'Selamat Tengahari 🌤️',
    'greeting.evening': 'Selamat Petang 🌅',
    'greeting.night': 'Selamat Malam 🌙',
    'greeting.latenight': 'Night owl? 🦉',
    'header.notifications': 'Notifikasi',
    'header.no_notif': 'Tiada notifikasi lagi',
    'header.notif_hint': 'Makluman aktiviti akan muncul di sini',
    'menu.profile': 'Profil Saya',
    'menu.language': 'Bahasa',
    'menu.signout': 'Log Keluar',
    'loading': 'Memuatkan NADI...',
    'levelup': 'NAIK TAHAP! 🎉',
    'levelup.desc': 'Anda kini Tahap',
    // Nav
    'nav.dashboard': 'Utama',
    'nav.infra': 'Infra',
    'nav.voice': 'Suara',
    'nav.bencana': 'Bencana',
    'nav.niaga': 'Niaga',
    'nav.madani': 'Malaysia MADANI',
    // Niaga
    'niaga.title': 'Nadi-Niaga',
    'niaga.subtitle': 'Rantaian Bekalan B2B Tempatan',
    'niaga.active_listings': 'Senarai Aktif',
    'niaga.listings': 'senarai',
    'niaga.connects': 'NADI menghubungkan pengeluar tempatan terus kepada peruncit. Yuran padanan B2B 2%.',
    'niaga.search': 'Cari bekalan tempatan (cth. \'Siakap\', \'Beras\')...',
    'niaga.live_log': 'Log Bekalan Langsung',
    'niaga.new': 'BAHARU ↑',
    'niaga.no_match': 'Tiada bekalan sepadan.',
    'niaga.no_listings': 'Belum ada senarai. Jadilah yang pertama!',
    'niaga.acquire': 'Dapatkan',
    'niaga.post': 'Hantar',
    'niaga.post_supply': 'Hantar Bekalan',
    'niaga.seller': 'Penjual',
    'niaga.item': 'Barangan',
    'niaga.price': 'Harga',
    'niaga.location': 'Lokasi',
    'niaga.category': 'Kategori',
    'niaga.post_listing': 'Hantar Senarai',
    'niaga.ai_verifying': 'AI Mengesahkan...',
    // Bencana
    'bencana.title': 'NADI Bencana',
    'bencana.subtitle': 'Laluan Krisis & Banjir Dinamik',
    'bencana.lorawan': 'Sonar LoRaWAN',
    'bencana.sensor_safe': 'LVL 1: SELAMAT',
    'bencana.sensor_warning': 'LVL 2: AMARAN',
    'bencana.sensor_danger': 'LVL 3: BAHAYA',
    'bencana.sensor_desc': 'Penderia aras air akan mengesan keadaan banjir secara automatik. Tiada pencetus manual — penderia LoRaWAN melaporkan secara langsung.',
    'bencana.evacuation': 'Pemindahan',
    'bencana.volunteer': 'Sukarelawan',
    'bencana.cleanup': 'Rangkaian Pembersihan Pasca-banjir',
    'bencana.request_help': 'Minta Bantuan',
    'bencana.no_requests': 'Tiada permintaan terbuka. Semua selamat!',
    'bencana.accept': 'TERIMA',
    'bencana.secured': 'DIJAMIN',
    'bencana.cancel': 'BATAL',
    'bencana.cancel_confirm': 'Pasti mahu batalkan permintaan ini?',
    'bencana.request_volunteers': 'Minta Sukarelawan',
    'bencana.household': 'Isi Rumah / Organisasi',
    'bencana.help_needed': 'Bantuan Diperlukan',
    'bencana.distance': 'Jarak (anggaran)',
    'bencana.area': 'Kawasan / Lokasi',
    'bencana.submit_request': 'Hantar Permintaan',
    'bencana.ai_priority': 'AI Menetapkan Keutamaan...',
    'bencana.active_route': 'Laluan Aktif',
    'bencana.standby': 'Sedia',
    'bencana.map_info': 'Peta GPS langsung aktif.',
    'bencana.priority': 'Keutamaan',
  },
  en: {
    'settings.title': 'Settings & Accessibility',
    'settings.subtitle': 'Customize your NADI experience',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme Mode',
    'settings.accessibility': 'Accessibility',
    'settings.scale': 'Interface Scale',
    'settings.scale_s': 'Standard',
    'settings.scale_m': 'Large',
    'settings.scale_l': 'Largest',
    'settings.dyslexia': 'Dyslexia Font',
    'settings.dyslexia_desc': 'Enhances text legibility and spacing',
    'settings.contrast': 'High Contrast',
    'settings.contrast_desc': 'Maximizes visual contrast of elements',
    'settings.motion': 'Reduce Motion',
    'settings.motion_desc': 'Disables UI animations and transitions',
    'settings.colorblind': 'Colorblind Filter',
    'settings.colorblind_desc': 'Adjust UI colors for color vision deficiencies',
    'settings.cb_none': 'Default Colors',
    'settings.tutorial': 'Replay Tutorial',
    'sivik.pass_title': 'Nadi-Pass',
    'sivik.pass_desc': 'Civic wallet & reputation',
    'sivik.pts_title': 'Civic Points',
    'sivik.pts_desc': 'Earn points through civic reports, volunteering & community participation',
    'sivik.trust': 'Trust',
    'sivik.quests': 'Quests',
    'sivik.badges': 'Badges',
    'sivik.crs_title': 'Civic Reputation Score',
    'sivik.tab_ledger': 'Activity Ledger',
    'sivik.tab_board': 'Leaderboard',
    'sivik.board_title': 'Community Leaderboard',
    'sivik.export_csv': 'Export CSV',
    'sivik.no_activity': 'No activity yet — start reporting to earn points!',
    'bantuan.title': 'Bantuan',
    'bantuan.desc': 'Aid & Volunteer',
    'bantuan.active_aid': 'Active Aid',
    'bantuan.volunteer': 'Volunteer',
    'bantuan.open_spots': 'Open Spots',
    'bantuan.tab_aid': 'Aid Programs',
    'bantuan.tab_vol': 'Volunteer',
    'bantuan.search_aid': 'Search aid programs...',
    'bantuan.no_aid': 'No aid programs found for your area',
    'bantuan.ai_title': 'AI Eligibility Check',
    'bantuan.ai_desc': 'Let NADI AI check which programs you are eligible for.',
    'bantuan.ai_btn': 'Check Now',
    'bantuan.profile': 'Applicant Profile',
    'bantuan.age': 'Age',
    'bantuan.income': 'Income (RM)',
    'bantuan.status': 'Status',
    'bantuan.dependents': 'Dependents',
    'bantuan.status_work': 'Employed',
    'bantuan.status_nowork': 'Unemployed',
    'bantuan.status_student': 'Student',
    'bantuan.status_retiree': 'Retiree',
    'bantuan.run_ai': 'Run AI Analysis',
    'bantuan.analyzing': 'Analyzing...',
    'bantuan.eligible': 'Eligible',
    'bantuan.not_eligible': 'Not Eligible',
    'bantuan.maybe_eligible': 'Maybe Eligible',
    'bantuan.provider': 'Provider:',
    'bantuan.visit_site': 'Visit Site →',
    'vol.urgent_sos': '🚨 Urgent Local SOS',
    'vol.no_sos': 'No local SOS requests',
    'vol.nationwide': '🤝 Nationwide Campaigns 🇲🇾',
    'vol.refresh': '↻ Refresh',
    'vol.search': 'Search by org, location, or role...',
    'vol.cat_all': 'All',
    'vol.cat_disaster': '🆘 Disaster',
    'vol.cat_edu': '📚 Education',
    'vol.cat_env': '🌿 Environment',
    'vol.cat_health': '🏥 Health',
    'vol.cat_comm': '🤝 Community',
    'vol.cat_elderly': '👵 Elderly',
    'vol.cat_youth': '⚡ Youth',
    'vol.finding': 'Finding volunteer opportunities...',
    'vol.no_match': 'No matching opportunities',
    'vol.try_diff': 'Try a different search or category',
    'vol.signup': 'Sign Up →',
    'vol.spots': 'spots',
    'vol.browse': '🔗 Browse Directly',
    'vol.visit_portals': 'Visit these official volunteer portals to find and sign up for specific activities:',
    // Tour
    'tour.skip': 'Skip Tour',
    'tour.next': 'Next',
    'tour.finish': 'Get Started 🚀',
    'tour.welcome_title': 'Welcome to NADI 🇲🇾',
    'tour.welcome_desc': 'Your all-in-one civic operations system. Let\'s take a quick tour.',
    'tour.bantuan_title': 'Bantuan — Aid & Volunteer',
    'tour.bantuan_desc': 'Find active government aid programs and browse real volunteer opportunities.',
    'tour.dashboard_title': 'Main Hub',
    'tour.dashboard_desc': 'Your center for weather, quests, and civic impact.',
    'tour.bencana_title': 'Disaster Center',
    'tour.bencana_desc': 'Get real-time disaster warnings and locate nearby evacuation centers.',
    'tour.suara_title': 'Suara — Your Voice',
    'tour.suara_desc': 'Report civic issues in local dialects. Our AI understands and routes them correctly.',
    'tour.infra_title': 'Infra & Bencana',
    'tour.infra_desc': 'Detect potholes while driving and monitor flood sensors in real-time.',
    'tour.heatmap_title': 'Civic Heatmap',
    'tour.heatmap_desc': 'View problem density and red zones around your area.',
    'tour.community_title': 'Community',
    'tour.community_desc': 'Join civic discussions and view recent community activities.',
    'tour.notif_title': 'Notifications',
    'tour.notif_desc': 'Receive updates on your reports and active flood warnings.',
    'tour.settings_title': 'Settings & Accessibility',
    'tour.settings_desc': 'Change languages, colorblind modes, dyslexia fonts, and themes here.',
    'greeting.morning': 'Good Morning! ☀️',
    'greeting.noon': 'Good Afternoon 🌤️',
    'greeting.evening': 'Good Evening 🌅',
    'greeting.night': 'Good Night 🌙',
    'greeting.latenight': 'Night owl? 🦉',
    'header.notifications': 'Notifications',
    'header.no_notif': 'No notifications yet',
    'header.notif_hint': 'Activity alerts will appear here',
    'menu.profile': 'My Profile',
    'menu.language': 'Language',
    'menu.signout': 'Sign Out',
    'loading': 'Loading NADI...',
    'levelup': 'LEVEL UP! 🎉',
    'levelup.desc': 'You are now Level',
    'nav.dashboard': 'Home',
    'nav.infra': 'Infra',
    'nav.voice': 'Voice',
    'nav.bencana': 'Disaster',
    'nav.niaga': 'Trade',
    'nav.madani': 'Malaysia MADANI',
    'niaga.title': 'Nadi-Niaga',
    'niaga.subtitle': 'Hyper-Local B2B Supply Chain',
    'niaga.active_listings': 'Active Listings',
    'niaga.listings': 'listings',
    'niaga.connects': 'NADI connects local producers directly to retailers. 2% verified B2B matching fee.',
    'niaga.search': "Search local supply (e.g., 'Siakap', 'Beras')...",
    'niaga.live_log': 'Live Supply Log',
    'niaga.new': 'NEW ↑',
    'niaga.no_match': 'No matching supply found.',
    'niaga.no_listings': 'No listings yet. Be the first to post!',
    'niaga.acquire': 'Acquire',
    'niaga.post': 'Post',
    'niaga.post_supply': 'Post Supply',
    'niaga.seller': 'Seller',
    'niaga.item': 'Item',
    'niaga.price': 'Price',
    'niaga.location': 'Location',
    'niaga.category': 'Category',
    'niaga.post_listing': 'Post Listing',
    'niaga.ai_verifying': 'AI Verifying...',
    'bencana.title': 'NADI Bencana',
    'bencana.subtitle': 'Dynamic Crisis & Flood Routing',
    'bencana.lorawan': 'LoRaWAN Sonar',
    'bencana.sensor_safe': 'LVL 1: SAFE',
    'bencana.sensor_warning': 'LVL 2: WARNING',
    'bencana.sensor_danger': 'LVL 3: DANGER',
    'bencana.sensor_desc': 'Water level sensors will auto-detect flood conditions. No manual trigger needed — LoRaWAN sensors report in real-time.',
    'bencana.evacuation': 'Evacuation',
    'bencana.volunteer': 'Volunteer',
    'bencana.cleanup': 'Post-flood Cleanup Network',
    'bencana.request_help': 'Request Help',
    'bencana.no_requests': 'No open requests. All clear!',
    'bencana.accept': 'ACCEPT',
    'bencana.secured': 'SECURED',
    'bencana.cancel': 'CANCEL',
    'bencana.cancel_confirm': 'Are you sure you want to cancel this request?',
    'bencana.request_volunteers': 'Request Volunteers',
    'bencana.household': 'Household / Organization',
    'bencana.help_needed': 'Help Needed',
    'bencana.distance': 'Distance (approx)',
    'bencana.area': 'Area / Location',
    'bencana.submit_request': 'Submit Request',
    'bencana.ai_priority': 'AI Assigning Priority...',
    'bencana.active_route': 'Active Route',
    'bencana.standby': 'Standby',
    'bencana.map_info': 'Live GPS mapping active.',
    'bencana.priority': 'Priority',
  },
  zh: {
    'settings.title': '设置与无障碍',
    'settings.subtitle': '自定义您的 NADI 体验',
    'settings.appearance': '外观',
    'settings.theme': '主题模式',
    'settings.accessibility': '无障碍',
    'settings.scale': '界面缩放',
    'settings.scale_s': '标准',
    'settings.scale_m': '大',
    'settings.scale_l': '最大',
    'settings.dyslexia': '阅读障碍字体',
    'settings.dyslexia_desc': '增强文本可读性和间距',
    'settings.contrast': '高对比度',
    'settings.contrast_desc': '最大化元素的视觉对比度',
    'settings.motion': '减少动态效果',
    'settings.motion_desc': '禁用UI动画和过渡',
    'settings.colorblind': '色盲滤镜',
    'settings.colorblind_desc': '为色觉缺陷调整UI颜色',
    'settings.cb_none': '默认颜色',
    'settings.tutorial': '重播教程',
    'sivik.pass_title': 'Nadi-Pass通行证',
    'sivik.pass_desc': '公民钱包与声誉',
    'sivik.pts_title': '公民积分',
    'sivik.pts_desc': '通过公民报告、志愿服务和社区参与赚取积分',
    'sivik.trust': '信任',
    'sivik.quests': '任务',
    'sivik.badges': '徽章',
    'sivik.crs_title': '公民声誉评分',
    'sivik.tab_ledger': '活动记录',
    'sivik.tab_board': '排行榜',
    'sivik.board_title': '社区排行榜',
    'sivik.export_csv': '导出 CSV',
    'sivik.no_activity': '暂无活动 — 开始报告以赚取积分！',
    'bantuan.title': '援助',
    'bantuan.desc': '援助与志愿服务',
    'bantuan.active_aid': '活跃援助',
    'bantuan.volunteer': '志愿者',
    'bantuan.open_spots': '开放名额',
    'bantuan.tab_aid': '援助计划',
    'bantuan.tab_vol': '志愿服务',
    'bantuan.search_aid': '搜索援助计划...',
    'bantuan.no_aid': '未找到适合您所在地区的援助计划',
    'bantuan.ai_title': 'AI 资格检查',
    'bantuan.ai_desc': '让 NADI AI 检查您符合申请条件的计划。',
    'bantuan.ai_btn': '立即检查',
    'bantuan.profile': '申请人资料',
    'bantuan.age': '年龄',
    'bantuan.income': '收入 (RM)',
    'bantuan.status': '状况',
    'bantuan.dependents': '受抚养人',
    'bantuan.status_work': '在职',
    'bantuan.status_nowork': '失业',
    'bantuan.status_student': '学生',
    'bantuan.status_retiree': '退休人员',
    'bantuan.run_ai': '运行 AI 分析',
    'bantuan.analyzing': '分析中...',
    'bantuan.eligible': '符合资格',
    'bantuan.not_eligible': '不符合资格',
    'bantuan.maybe_eligible': '可能符合',
    'bantuan.provider': '提供者：',
    'bantuan.visit_site': '访问网站 →',
    'vol.urgent_sos': '🚨 紧急本地求救',
    'vol.no_sos': '没有本地求救请求',
    'vol.nationwide': '🤝 全国活动 🇲🇾',
    'vol.refresh': '↻ 刷新',
    'vol.search': '按组织、地点或角色搜索...',
    'vol.cat_all': '全部',
    'vol.cat_disaster': '🆘 灾害',
    'vol.cat_edu': '📚 教育',
    'vol.cat_env': '🌿 环境',
    'vol.cat_health': '🏥 健康',
    'vol.cat_comm': '🤝 社区',
    'vol.cat_elderly': '👵 老年人',
    'vol.cat_youth': '⚡ 青年',
    'vol.finding': '正在寻找志愿服务机会...',
    'vol.no_match': '没有匹配的机会',
    'vol.try_diff': '尝试不同的搜索或分类',
    'vol.signup': '报名 →',
    'vol.spots': '名额',
    'vol.browse': '🔗 直接浏览',
    'vol.visit_portals': '访问这些官方志愿者门户网站以查找并报名参加具体活动：',
    // Tour
    'tour.skip': '跳过',
    'tour.next': '下一步',
    'tour.finish': '开始 🚀',
    'tour.welcome_title': '欢迎来到 NADI 🇲🇾',
    'tour.welcome_desc': '您的一站式公民操作系统。让我们快速浏览一下。',
    'tour.bantuan_title': '援助与志愿服务',
    'tour.bantuan_desc': '查找活跃的政府援助项目，浏览真实的志愿者机会。',
    'tour.dashboard_title': '主中心',
    'tour.dashboard_desc': '您的天气、任务和公民影响中心。',
    'tour.bencana_title': '灾难中心',
    'tour.bencana_desc': '获取实时灾难警告并定位附近的疏散中心。',
    'tour.suara_title': '您的声音 (吹哨人)',
    'tour.suara_desc': '用方言举报问题。我们的 AI 能够理解并将其发送给正确的部门。',
    'tour.infra_title': '基础设施与热力图',
    'tour.infra_desc': '驾驶时检测坑洼，并实时监控洪水传感器。',
    'tour.heatmap_title': '公民热力图',
    'tour.heatmap_desc': '查看您所在地区的问题密度和红区。',
    'tour.community_title': '社区活动',
    'tour.community_desc': '加入公民讨论并查看最近的社区活动。',
    'tour.notif_title': '通知中心',
    'tour.notif_desc': '接收有关您的举报和洪水警告的更新。',
    'tour.settings_title': '设置与无障碍',
    'tour.settings_desc': '在此处更改语言、色盲模式、阅读障碍字体和主题。',
    'greeting.morning': '早上好！☀️',
    'greeting.noon': '午安 🌤️',
    'greeting.evening': '傍晚好 🌅',
    'greeting.night': '晚安 🌙',
    'greeting.latenight': '夜猫子？🦉',
    'header.notifications': '通知',
    'header.no_notif': '暂无通知',
    'header.notif_hint': '活动提醒将在此显示',
    'menu.profile': '我的个人资料',
    'menu.language': '语言',
    'menu.signout': '退出登录',
    'loading': '加载NADI中...',
    'levelup': '升级！🎉',
    'levelup.desc': '您现在是等级',
    'nav.dashboard': '主页',
    'nav.infra': '基础设施',
    'nav.voice': '声音',
    'nav.bencana': '灾害',
    'nav.niaga': '商业',
    'nav.madani': '马来西亚 MADANI',
    'niaga.title': 'Nadi-贸易',
    'niaga.subtitle': '超本地B2B供应链',
    'niaga.active_listings': '活跃列表',
    'niaga.listings': '个列表',
    'niaga.connects': 'NADI将本地生产者直接连接到零售商。2%认证B2B匹配费。',
    'niaga.search': '搜索本地供应（如"石甲鱼"、"大米"）...',
    'niaga.live_log': '实时供应日志',
    'niaga.new': '新 ↑',
    'niaga.no_match': '未找到匹配的供应。',
    'niaga.no_listings': '暂无列表。成为第一个发布者！',
    'niaga.acquire': '获取',
    'niaga.post': '发布',
    'niaga.post_supply': '发布供应',
    'niaga.seller': '卖家',
    'niaga.item': '商品',
    'niaga.price': '价格',
    'niaga.location': '地点',
    'niaga.category': '类别',
    'niaga.post_listing': '发布列表',
    'niaga.ai_verifying': 'AI验证中...',
    'bencana.title': 'NADI 灾害',
    'bencana.subtitle': '动态危机与洪水路线',
    'bencana.lorawan': 'LoRaWAN声纳',
    'bencana.sensor_safe': '1级：安全',
    'bencana.sensor_warning': '2级：警告',
    'bencana.sensor_danger': '3级：危险',
    'bencana.sensor_desc': '水位传感器将自动检测洪水状况。无需手动触发——LoRaWAN传感器实时报告。',
    'bencana.evacuation': '疏散',
    'bencana.volunteer': '志愿者',
    'bencana.cleanup': '洪后清理网络',
    'bencana.request_help': '请求帮助',
    'bencana.no_requests': '没有未处理的请求。一切正常！',
    'bencana.accept': '接受',
    'bencana.secured': '已确保',
    'bencana.cancel': '取消',
    'bencana.cancel_confirm': '确定要取消此请求吗？',
    'bencana.request_volunteers': '请求志愿者',
    'bencana.household': '家庭/组织',
    'bencana.help_needed': '需要的帮助',
    'bencana.distance': '距离（大约）',
    'bencana.area': '区域/地点',
    'bencana.submit_request': '提交请求',
    'bencana.ai_priority': 'AI分配优先级...',
    'bencana.active_route': '活跃路线',
    'bencana.standby': '待命',
    'bencana.map_info': '实时GPS地图已激活。',
    'bencana.priority': '优先级',
  },
  ta: {
    'settings.title': 'அமைப்புகள் & அணுகல்',
    'settings.subtitle': 'உங்கள் NADI அனுபவத்தைத் தனிப்பயனாக்குங்கள்',
    'settings.appearance': 'தோற்றம்',
    'settings.theme': 'தீம் முறை',
    'settings.accessibility': 'அணுகல்',
    'settings.scale': 'இடைமுக அளவு',
    'settings.scale_s': 'நிலையானது',
    'settings.scale_m': 'பெரியது',
    'settings.scale_l': 'மிகப் பெரியது',
    'settings.dyslexia': 'டிஸ்லெக்ஸியா எழுத்துரு',
    'settings.dyslexia_desc': 'உரை வாசிப்புத்திறன் மற்றும் இடைவெளியை மேம்படுத்துகிறது',
    'settings.contrast': 'அதிக வேறுபாடு',
    'settings.contrast_desc': 'கூறுகளின் காட்சி வேறுபாட்டை அதிகப்படுத்துகிறது',
    'settings.motion': 'இயக்கத்தைக் குறை',
    'settings.motion_desc': 'UI அனிமேஷன்கள் மற்றும் மாற்றங்களை முடக்குகிறது',
    'settings.colorblind': 'வண்ணக்குருடு வடிப்பான்',
    'settings.colorblind_desc': 'வண்ணப் பார்வை குறைபாடுகளுக்கு UI வண்ணங்களைச் சரிசெய்யவும்',
    'settings.cb_none': 'இயல்புநிலை வண்ணங்கள்',
    'settings.tutorial': 'பயிற்சியை மீண்டும் இயக்கு',
    'sivik.pass_title': 'Nadi-Pass',
    'sivik.pass_desc': 'சிவில் வாலெட் மற்றும் நற்பெயர்',
    'sivik.pts_title': 'சிவில் புள்ளிகள்',
    'sivik.pts_desc': 'குடிமக்கள் அறிக்கைகள், தன்னார்வத் தொண்டு மற்றும் சமூகப் பங்கேற்பு மூலம் புள்ளிகளைப் பெறுங்கள்',
    'sivik.trust': 'நம்பிக்கை',
    'sivik.quests': 'தேடல்கள்',
    'sivik.badges': 'சின்னங்கள்',
    'sivik.crs_title': 'குடிமக்கள் நற்பெயர் மதிப்பெண்',
    'sivik.tab_ledger': 'செயல்பாட்டு லெட்ஜர்',
    'sivik.tab_board': 'லீடர்போர்டு',
    'sivik.board_title': 'சமூக லீடர்போர்டு',
    'sivik.export_csv': 'CSV ஏற்றுமதி',
    'sivik.no_activity': 'செயல்பாடுகள் இல்லை — புள்ளிகளைப் பெறத் தொடங்குங்கள்!',
    'bantuan.title': 'உதவி',
    'bantuan.desc': 'உதவி & தன்னார்வ',
    'bantuan.active_aid': 'சுறுசுறுப்பான உதவி',
    'bantuan.volunteer': 'தன்னார்வலர்',
    'bantuan.open_spots': 'திறந்த இடங்கள்',
    'bantuan.tab_aid': 'உதவி திட்டங்கள்',
    'bantuan.tab_vol': 'தன்னார்வலர்',
    'bantuan.search_aid': 'உதவி திட்டங்களைத் தேடுங்கள்...',
    'bantuan.no_aid': 'உங்கள் பகுதியில் எந்த உதவித் திட்டங்களும் கிடைக்கவில்லை',
    'bantuan.ai_title': 'AI தகுதி சரிபார்ப்பு',
    'bantuan.ai_desc': 'நீங்கள் எந்த திட்டங்களுக்கு தகுதியானவர் என்பதை NADI AI சரிபார்க்கட்டும்.',
    'bantuan.ai_btn': 'இப்போது சரிபார்க்கவும்',
    'bantuan.provider': 'வழங்குநர்:',
    'bantuan.visit_site': 'தளத்தைப் பார்வையிடவும் →',
    'vol.urgent_sos': '🚨 அவசர உள்ளூர் SOS',
    'vol.no_sos': 'உள்ளூர் SOS கோரிக்கைகள் இல்லை',
    'vol.nationwide': '🤝 நாடு தழுவிய பிரச்சாரங்கள் 🇲🇾',
    'vol.refresh': '↻ புதுப்பி',
    'vol.search': 'நிறுவனம், இடம் அல்லது பங்கு மூலம் தேடவும்...',
    'vol.cat_all': 'அனைத்தும்',
    'vol.cat_disaster': '🆘 பேரிடர்',
    'vol.cat_edu': '📚 கல்வி',
    'vol.cat_env': '🌿 சுற்றுச்சூழல்',
    'vol.cat_health': '🏥 ஆரோக்கியம்',
    'vol.cat_comm': '🤝 சமூகம்',
    'vol.cat_elderly': '👵 முதியோர்',
    'vol.cat_youth': '⚡ இளைஞர்கள்',
    'vol.finding': 'தன்னார்வ வாய்ப்புகளை தேடுகிறது...',
    'vol.no_match': 'பொருத்தமான வாய்ப்புகள் இல்லை',
    'vol.try_diff': 'வேறு தேடல் அல்லது வகையை முயற்சிக்கவும்',
    'vol.signup': 'பதிவு செய் →',
    'vol.spots': 'இடங்கள்',
    'vol.browse': '🔗 நேரடியாக உலாவுக',
    'vol.visit_portals': 'குறிப்பிட்ட செயல்பாடுகளைக் கண்டறிந்து பதிவுசெய்ய இந்த அதிகாரப்பூர்வ தன்னார்வ தளங்களைப் பார்வையிடவும்:',
    // Tour
    'tour.skip': 'தவிர்',
    'tour.next': 'அடுத்து',
    'tour.finish': 'தொடங்கு 🚀',
    'tour.welcome_title': 'NADI-க்கு வரவேற்கிறோம் 🇲🇾',
    'tour.welcome_desc': 'உங்கள் ஆல்-இன்-ஒன் குடிமக்கள் அமைப்பு. விரைவான சுற்றுப்பயணம் செல்வோம்.',
    'tour.bantuan_title': 'உதவி மற்றும் தன்னார்வத் தொண்டு',
    'tour.bantuan_desc': 'அரசு உதவித் திட்டங்களைக் கண்டறிந்து தன்னார்வ வாய்ப்புகளை உலாவுக.',
    'tour.dashboard_title': 'முக்கிய மையம்',
    'tour.dashboard_desc': 'வானிலை, தேடல்கள் மற்றும் சிவில் தாக்கத்திற்கான உங்கள் மையம்.',
    'tour.bencana_title': 'பேரிடர் மையம்',
    'tour.bencana_desc': 'நிகழ்நேர பேரிடர் எச்சரிக்கைகளைப் பெறுங்கள் மற்றும் மீட்பு மையங்களைக் கண்டறியவும்.',
    'tour.suara_title': 'உங்கள் குரல்',
    'tour.suara_desc': 'உள்ளூர் பேச்சுவழக்குகளில் சிவில் பிரச்சினைகளைப் புகாரளிக்கவும்.',
    'tour.infra_title': 'உள்கட்டமைப்பு & பேரிடர்',
    'tour.infra_desc': 'வாகனம் ஓட்டும்போது குழிகளைக் கண்டறிந்து வெள்ள உணரிக கண்காணிக்கவும்.',
    'tour.heatmap_title': 'வெப்ப வரைபடம்',
    'tour.heatmap_desc': 'உங்கள் பகுதியில் உள்ள பிரச்சனை அடர்த்தியைப் பார்க்கவும்.',
    'tour.community_title': 'சமூகம்',
    'tour.community_desc': 'சிவில் விவாதங்களில் சேர்ந்து சமூக செயல்பாடுகளைக் காணுங்கள்.',
    'tour.notif_title': 'அறிவிப்புகள்',
    'tour.notif_desc': 'உங்கள் புகார்கள் மற்றும் வெள்ள எச்சரிக்கைகள் பற்றிய அறிவிப்புகளைப் பெறவும்.',
    'tour.settings_title': 'அமைப்புகள் & அணுகல்',
    'tour.settings_desc': 'மொழிகள், நிறக்குருடு முறைகள், மற்றும் கருப்பொருள்களை மாற்றவும்.',
    'greeting.morning': 'காலை வணக்கம்! ☀️',
    'greeting.noon': 'மதிய வணக்கம் 🌤️',
    'greeting.evening': 'மாலை வணக்கம் 🌅',
    'greeting.night': 'இரவு வணக்கம் 🌙',
    'greeting.latenight': 'இரவு ஆந்தையா? 🦉',
    'header.notifications': 'அறிவிப்புகள்',
    'header.no_notif': 'இன்னும் அறிவிப்புகள் இல்லை',
    'header.notif_hint': 'செயல்பாட்டு எச்சரிக்கைகள் இங்கே தோன்றும்',
    'menu.profile': 'எனது சுயவிவரம்',
    'menu.language': 'மொழி',
    'menu.signout': 'வெளியேறு',
    'loading': 'NADI ஏற்றுகிறது...',
    'levelup': 'நிலை உயர்வு! 🎉',
    'levelup.desc': 'நீங்கள் இப்போது நிலை',
    'nav.dashboard': 'முகப்பு',
    'nav.infra': 'உள்கட்டமைப்பு',
    'nav.voice': 'குரல்',
    'nav.bencana': 'பேரிடர்',
    'nav.niaga': 'வணிகம்',
    'niaga.title': 'Nadi-வணிகம்',
    'niaga.subtitle': 'உள்ளூர் B2B விநியோகச் சங்கிலி',
    'niaga.active_listings': 'செயலில் உள்ள பட்டியல்கள்',
    'niaga.listings': 'பட்டியல்கள்',
    'niaga.connects': 'NADI உள்ளூர் உற்பத்தியாளர்களை நேரடியாக சில்லறை விற்பனையாளர்களுடன் இணைக்கிறது.',
    'niaga.search': 'உள்ளூர் வழங்கலைத் தேடுங்கள்...',
    'niaga.live_log': 'நேரடி வழங்கல் பதிவு',
    'niaga.new': 'புதியது ↑',
    'niaga.no_match': 'பொருத்தமான வழங்கல் இல்லை.',
    'niaga.no_listings': 'இன்னும் பட்டியல்கள் இல்லை. முதலில் பதிவிடுங்கள்!',
    'niaga.acquire': 'பெறுக',
    'niaga.post': 'பதிவிடு',
    'niaga.post_supply': 'வழங்கலைப் பதிவிடு',
    'niaga.seller': 'விற்பனையாளர்',
    'niaga.item': 'பொருள்',
    'niaga.price': 'விலை',
    'niaga.location': 'இடம்',
    'niaga.category': 'வகை',
    'niaga.post_listing': 'பட்டியலைப் பதிவிடு',
    'niaga.ai_verifying': 'AI சரிபார்க்கிறது...',
    'bencana.title': 'NADI பேரிடர்',
    'bencana.subtitle': 'மாறும் நெருக்கடி & வெள்ள வழி',
    'bencana.lorawan': 'LoRaWAN சோனார்',
    'bencana.sensor_safe': 'நிலை 1: பாதுகாப்பு',
    'bencana.sensor_warning': 'நிலை 2: எச்சரிக்கை',
    'bencana.sensor_danger': 'நிலை 3: ஆபத்து',
    'bencana.sensor_desc': 'நீர்மட்ட உணரிகள் வெள்ள நிலைமைகளை தானாக கண்டறியும்.',
    'bencana.evacuation': 'வெளியேற்றம்',
    'bencana.volunteer': 'தன்னார்வலர்',
    'bencana.cleanup': 'வெள்ளத்திற்குப் பிந்தைய சுத்திகரிப்பு',
    'bencana.request_help': 'உதவி கேள்',
    'bencana.no_requests': 'திறந்த கோரிக்கைகள் இல்லை. அனைத்தும் சரி!',
    'bencana.accept': 'ஏற்கவும்',
    'bencana.secured': 'பாதுகாக்கப்பட்டது',
    'bencana.cancel': 'ரத்து',
    'bencana.cancel_confirm': 'இந்தக் கோரிக்கையை ரத்து செய்ய விரும்புகிறீர்களா?',
    'bencana.request_volunteers': 'தன்னார்வலர்களைக் கோரு',
    'bencana.household': 'குடும்பம் / அமைப்பு',
    'bencana.help_needed': 'தேவையான உதவி',
    'bencana.distance': 'தூரம் (தோராயம்)',
    'bencana.area': 'பகுதி / இடம்',
    'bencana.submit_request': 'கோரிக்கையை சமர்ப்பி',
    'bencana.ai_priority': 'AI முன்னுரிமை அமைக்கிறது...',
    'bencana.active_route': 'செயலில் வழி',
    'bencana.standby': 'தயார்நிலை',
    'bencana.map_info': 'நேரடி GPS வரைபடம் செயலில்.',
    'bencana.priority': 'முன்னுரிமை',
  },
  ar: {
    'settings.title': 'الإعدادات وإمكانية الوصول',
    'settings.subtitle': 'تخصيص تجربة NADI الخاصة بك',
    'settings.appearance': 'المظهر',
    'settings.theme': 'وضع المظهر',
    'settings.accessibility': 'إمكانية الوصول',
    'settings.scale': 'حجم الواجهة',
    'settings.scale_s': 'قياسي',
    'settings.scale_m': 'كبير',
    'settings.scale_l': 'الأكبر',
    'settings.dyslexia': 'خط عسر القراءة',
    'settings.dyslexia_desc': 'يعزز وضوح النص وتباعده',
    'settings.contrast': 'تباين عالي',
    'settings.contrast_desc': 'يزيد من التباين البصري للعناصر',
    'settings.motion': 'تقليل الحركة',
    'settings.motion_desc': 'يعطل الرسوم المتحركة والانتقالات في واجهة المستخدم',
    'settings.colorblind': 'فلتر عمى الألوان',
    'settings.colorblind_desc': 'ضبط ألوان واجهة المستخدم لنقص رؤية الألوان',
    'settings.cb_none': 'الألوان الافتراضية',
    'settings.tutorial': 'إعادة تشغيل البرنامج التعليمي',
    'sivik.pass_title': 'Nadi-Pass',
    'sivik.pass_desc': 'المحفظة المدنية والسمعة',
    'sivik.pts_title': 'النقاط المدنية',
    'sivik.pts_desc': 'اجمع النقاط من خلال التقارير المدنية والعمل التطوعي والمشاركة المجتمعية',
    'sivik.trust': 'ثقة',
    'sivik.quests': 'المهام',
    'sivik.badges': 'الشارات',
    'sivik.crs_title': 'درجة السمعة المدنية',
    'sivik.tab_ledger': 'سجل النشاط',
    'sivik.tab_board': 'لائحة المتصدرين',
    'sivik.board_title': 'لائحة المتصدرين المجتمعية',
    'sivik.export_csv': 'تصدير CSV',
    'sivik.no_activity': 'لا يوجد نشاط حتى الآن — ابدأ في الإبلاغ لكسب النقاط!',
    'bantuan.title': 'مساعدة',
    'bantuan.desc': 'المساعدة والتطوع',
    'bantuan.active_aid': 'المساعدة النشطة',
    'bantuan.volunteer': 'تطوع',
    'bantuan.open_spots': 'الأماكن المفتوحة',
    'bantuan.tab_aid': 'برامج المساعدة',
    'bantuan.tab_vol': 'تطوع',
    'bantuan.search_aid': 'البحث في برامج المساعدة...',
    'bantuan.no_aid': 'لم يتم العثور على برامج مساعدة في منطقتك',
    'bantuan.ai_title': 'التحقق من الأهلية بالذكاء الاصطناعي',
    'bantuan.ai_desc': 'دع الذكاء الاصطناعي يتحقق من البرامج التي تؤهلك.',
    'bantuan.ai_btn': 'تحقق الآن',
    'bantuan.provider': 'مزود:',
    'bantuan.visit_site': 'زيارة الموقع ←',
    'vol.urgent_sos': '🚨 نداء استغاثة محلي عاجل',
    'vol.no_sos': 'لا توجد طلبات استغاثة محلية',
    'vol.nationwide': '🤝 حملات على مستوى البلاد 🇲🇾',
    'vol.refresh': '↻ تحديث',
    'vol.search': 'البحث حسب المنظمة، الموقع، أو الدور...',
    'vol.cat_all': 'الكل',
    'vol.cat_disaster': '🆘 كوارث',
    'vol.cat_edu': '📚 تعليم',
    'vol.cat_env': '🌿 بيئة',
    'vol.cat_health': '🏥 صحة',
    'vol.cat_comm': '🤝 مجتمع',
    'vol.cat_elderly': '👵 كبار السن',
    'vol.cat_youth': '⚡ شباب',
    'vol.finding': 'جاري البحث عن فرص التطوع...',
    'vol.no_match': 'لا توجد فرص مطابقة',
    'vol.try_diff': 'جرب بحثًا أو فئة مختلفة',
    'vol.signup': 'التسجيل ←',
    'vol.spots': 'أماكن',
    'vol.browse': '🔗 تصفح مباشرة',
    'vol.visit_portals': 'قم بزيارة بوابات التطوع الرسمية هذه للعثور على الأنشطة المحددة والتسجيل فيها:',
    // Tour
    'tour.skip': 'تخطي',
    'tour.next': 'التالي',
    'tour.finish': 'ابدأ 🚀',
    'tour.welcome_title': 'مرحبًا بك في NADI 🇲🇾',
    'tour.welcome_desc': 'نظام العمليات المدنية الشامل الخاص بك. دعنا نأخذ جولة سريعة.',
    'tour.bantuan_title': 'المساعدات والتطوع',
    'tour.bantuan_desc': 'ابحث عن برامج المساعدات الحكومية وتصفح فرص التطوع.',
    'tour.dashboard_title': 'المركز الرئيسي',
    'tour.dashboard_desc': 'مركزك للطقس والمهام والتأثير المدني.',
    'tour.bencana_title': 'مركز الكوارث',
    'tour.bencana_desc': 'احصل على تحذيرات الكوارث في الوقت الفعلي وحدد مواقع مراكز الإخلاء.',
    'tour.suara_title': 'صوتك (المُبلّغ)',
    'tour.suara_desc': 'الإبلاغ عن المشاكل المدنية باللغات المحلية. الذكاء الاصطناعي يفهمها.',
    'tour.infra_title': 'البنية التحتية والكوارث',
    'tour.infra_desc': 'اكتشف الحفر وراقب مجسات الفيضانات في الوقت الفعلي.',
    'tour.heatmap_title': 'الخريطة الحرارية',
    'tour.heatmap_desc': 'عرض كثافة المشاكل والمناطق الحمراء في منطقتتك.',
    'tour.community_title': 'المجتمع',
    'tour.community_desc': 'انضم إلى المناقشات المدنية واعرض أنشطة المجتمع الأخيرة.',
    'tour.notif_title': 'الإشعارات',
    'tour.notif_desc': 'تلقي تحديثات حول تقاريرك وتحذيرات الفيضانات النشطة.',
    'tour.settings_title': 'الإعدادات وسهولة الوصول',
    'tour.settings_desc': 'قم بتغيير اللغات وأنماط عمى الألوان والخطوط والسمات هنا.',
    'greeting.morning': 'صباح الخير! ☀️',
    'greeting.noon': 'مساء الخير 🌤️',
    'greeting.evening': 'مساء الخير 🌅',
    'greeting.night': 'مساء الخير 🌙',
    'greeting.latenight': 'بومة ليلية؟ 🦉',
    'header.notifications': 'الإشعارات',
    'header.no_notif': 'لا توجد إشعارات بعد',
    'header.notif_hint': 'ستظهر تنبيهات النشاط هنا',
    'menu.profile': 'ملفي الشخصي',
    'menu.language': 'اللغة',
    'menu.signout': 'تسجيل الخروج',
    'loading': 'جاري تحميل NADI...',
    'levelup': 'ترقية! 🎉',
    'levelup.desc': 'أنت الآن في المستوى',
    'nav.dashboard': 'الرئيسية',
    'nav.infra': 'البنية التحتية',
    'nav.voice': 'الصوت',
    'nav.bencana': 'الكوارث',
    'nav.niaga': 'التجارة',
    'niaga.title': 'نادي-التجارة',
    'niaga.subtitle': 'سلسلة التوريد المحلية B2B',
    'niaga.active_listings': 'القوائم النشطة',
    'niaga.listings': 'قائمة',
    'niaga.connects': 'NADI يربط المنتجين المحليين مباشرة بالتجار. رسوم مطابقة B2B 2%.',
    'niaga.search': 'ابحث في الإمدادات المحلية...',
    'niaga.live_log': 'سجل الإمداد المباشر',
    'niaga.new': 'جديد ↑',
    'niaga.no_match': 'لم يتم العثور على إمداد مطابق.',
    'niaga.no_listings': 'لا توجد قوائم بعد. كن أول من ينشر!',
    'niaga.acquire': 'احصل',
    'niaga.post': 'نشر',
    'niaga.post_supply': 'نشر الإمداد',
    'niaga.seller': 'البائع',
    'niaga.item': 'المنتج',
    'niaga.price': 'السعر',
    'niaga.location': 'الموقع',
    'niaga.category': 'الفئة',
    'niaga.post_listing': 'نشر القائمة',
    'niaga.ai_verifying': 'AI يتحقق...',
    'bencana.title': 'NADI الكوارث',
    'bencana.subtitle': 'مسار الأزمات والفيضانات الديناميكي',
    'bencana.lorawan': 'سونار LoRaWAN',
    'bencana.sensor_safe': 'المستوى 1: آمن',
    'bencana.sensor_warning': 'المستوى 2: تحذير',
    'bencana.sensor_danger': 'المستوى 3: خطر',
    'bencana.sensor_desc': 'ستكتشف مستشعرات مستوى المياه ظروف الفيضان تلقائيًا.',
    'bencana.evacuation': 'الإخلاء',
    'bencana.volunteer': 'المتطوعون',
    'bencana.cleanup': 'شبكة تنظيف ما بعد الفيضان',
    'bencana.request_help': 'طلب مساعدة',
    'bencana.no_requests': 'لا توجد طلبات مفتوحة. الوضع آمن!',
    'bencana.accept': 'قبول',
    'bencana.secured': 'مؤمّن',
    'bencana.cancel': 'إلغاء',
    'bencana.cancel_confirm': 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟',
    'bencana.request_volunteers': 'طلب متطوعين',
    'bencana.household': 'الأسرة / المنظمة',
    'bencana.help_needed': 'المساعدة المطلوبة',
    'bencana.distance': 'المسافة (تقريبًا)',
    'bencana.area': 'المنطقة / الموقع',
    'bencana.submit_request': 'إرسال الطلب',
    'bencana.ai_priority': 'AI يحدد الأولوية...',
    'bencana.active_route': 'المسار النشط',
    'bencana.standby': 'استعداد',
    'bencana.map_info': 'خريطة GPS مباشرة نشطة.',
    'bencana.priority': 'الأولوية',
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'ms',
  setLang: () => { },
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('ms');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('nadi_lang') as LangCode | null;
      if (saved && translations[saved]) setLangState(saved);
    } catch { /* ignore */ }
  }, []);

  const setLang = (code: LangCode) => {
    setLangState(code);
    try { localStorage.setItem('nadi_lang', code); } catch { /* ignore */ }
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
