'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LangCode = 'ms' | 'en' | 'zh' | 'ta' | 'ar';

export const LANGUAGES: { code: LangCode; label: string; flag: string }[] = [
  { code: 'ms', label: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'ta', label: 'தமிழ்', flag: '🇮🇳' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
];

const translations: Record<LangCode, Record<string, string>> = {
  ms: {
    // Header
    'greeting.morning': 'Selamat Pagi! ☀️',
    'greeting.noon': 'Selamat Tengahari 🌤️',
    'greeting.evening': 'Selamat Petang 🌅',
    'greeting.night': 'Selamat Malam 🌙',
    'greeting.latenight': 'Night owl? 🦉',
    'header.notifications': 'Notifikasi',
    'header.no_notif': 'Tiada notifikasi lagi',
    'header.notif_hint': 'Makluman aktiviti akan muncul di sini',
    'menu.profile': 'Profil Saya',
    'menu.language': 'Bahasa',
    'menu.signout': 'Log Keluar',
    'loading': 'Memuatkan NADI...',
    'levelup': 'NAIK TAHAP! 🎉',
    'levelup.desc': 'Anda kini Tahap',
    // Nav
    'nav.nadipass': 'Nadi-Pass',
    'nav.infra': 'Infra',
    'nav.voice': 'Suara',
    'nav.bencana': 'Bencana',
    'nav.niaga': 'Niaga',
    // Niaga
    'niaga.title': 'Nadi-Niaga',
    'niaga.subtitle': 'Rantaian Bekalan B2B Tempatan',
    'niaga.active_listings': 'Senarai Aktif',
    'niaga.listings': 'senarai',
    'niaga.connects': 'NADI menghubungkan pengeluar tempatan terus kepada peruncit. Yuran padanan B2B 2%.',
    'niaga.search': 'Cari bekalan tempatan (cth. \'Siakap\', \'Beras\')...',
    'niaga.live_log': 'Log Bekalan Langsung',
    'niaga.new': 'BAHARU ↑',
    'niaga.no_match': 'Tiada bekalan sepadan.',
    'niaga.no_listings': 'Belum ada senarai. Jadilah yang pertama!',
    'niaga.acquire': 'Dapatkan',
    'niaga.post': 'Hantar',
    'niaga.post_supply': 'Hantar Bekalan',
    'niaga.seller': 'Penjual',
    'niaga.item': 'Barangan',
    'niaga.price': 'Harga',
    'niaga.location': 'Lokasi',
    'niaga.category': 'Kategori',
    'niaga.post_listing': 'Hantar Senarai',
    'niaga.ai_verifying': 'AI Mengesahkan...',
    // Bencana
    'bencana.title': 'NADI Bencana',
    'bencana.subtitle': 'Laluan Krisis & Banjir Dinamik',
    'bencana.lorawan': 'Sonar LoRaWAN',
    'bencana.sensor_safe': 'LVL 1: SELAMAT',
    'bencana.sensor_warning': 'LVL 2: AMARAN',
    'bencana.sensor_danger': 'LVL 3: BAHAYA',
    'bencana.sensor_desc': 'Penderia aras air akan mengesan keadaan banjir secara automatik. Tiada pencetus manual — penderia LoRaWAN melaporkan secara langsung.',
    'bencana.evacuation': 'Pemindahan',
    'bencana.volunteer': 'Sukarelawan',
    'bencana.cleanup': 'Rangkaian Pembersihan Pasca-banjir',
    'bencana.request_help': 'Minta Bantuan',
    'bencana.no_requests': 'Tiada permintaan terbuka. Semua selamat!',
    'bencana.accept': 'TERIMA',
    'bencana.secured': 'DIJAMIN',
    'bencana.cancel': 'BATAL',
    'bencana.cancel_confirm': 'Pasti mahu batalkan permintaan ini?',
    'bencana.request_volunteers': 'Minta Sukarelawan',
    'bencana.household': 'Isi Rumah / Organisasi',
    'bencana.help_needed': 'Bantuan Diperlukan',
    'bencana.distance': 'Jarak (anggaran)',
    'bencana.area': 'Kawasan / Lokasi',
    'bencana.submit_request': 'Hantar Permintaan',
    'bencana.ai_priority': 'AI Menetapkan Keutamaan...',
    'bencana.active_route': 'Laluan Aktif',
    'bencana.standby': 'Sedia',
    'bencana.map_info': 'Peta GPS langsung aktif.',
    'bencana.priority': 'Keutamaan',
  },
  en: {
    'greeting.morning': 'Good Morning! ☀️',
    'greeting.noon': 'Good Afternoon 🌤️',
    'greeting.evening': 'Good Evening 🌅',
    'greeting.night': 'Good Night 🌙',
    'greeting.latenight': 'Night owl? 🦉',
    'header.notifications': 'Notifications',
    'header.no_notif': 'No notifications yet',
    'header.notif_hint': 'Activity alerts will appear here',
    'menu.profile': 'My Profile',
    'menu.language': 'Language',
    'menu.signout': 'Sign Out',
    'loading': 'Loading NADI...',
    'levelup': 'LEVEL UP! 🎉',
    'levelup.desc': 'You are now Level',
    'nav.nadipass': 'Nadi-Pass',
    'nav.infra': 'Infra',
    'nav.voice': 'Voice',
    'nav.bencana': 'Bencana',
    'nav.niaga': 'Niaga',
    'niaga.title': 'Nadi-Niaga',
    'niaga.subtitle': 'Hyper-Local B2B Supply Chain',
    'niaga.active_listings': 'Active Listings',
    'niaga.listings': 'listings',
    'niaga.connects': 'NADI connects local producers directly to retailers. 2% verified B2B matching fee.',
    'niaga.search': "Search local supply (e.g., 'Siakap', 'Beras')...",
    'niaga.live_log': 'Live Supply Log',
    'niaga.new': 'NEW ↑',
    'niaga.no_match': 'No matching supply found.',
    'niaga.no_listings': 'No listings yet. Be the first to post!',
    'niaga.acquire': 'Acquire',
    'niaga.post': 'Post',
    'niaga.post_supply': 'Post Supply',
    'niaga.seller': 'Seller',
    'niaga.item': 'Item',
    'niaga.price': 'Price',
    'niaga.location': 'Location',
    'niaga.category': 'Category',
    'niaga.post_listing': 'Post Listing',
    'niaga.ai_verifying': 'AI Verifying...',
    'bencana.title': 'NADI Bencana',
    'bencana.subtitle': 'Dynamic Crisis & Flood Routing',
    'bencana.lorawan': 'LoRaWAN Sonar',
    'bencana.sensor_safe': 'LVL 1: SAFE',
    'bencana.sensor_warning': 'LVL 2: WARNING',
    'bencana.sensor_danger': 'LVL 3: DANGER',
    'bencana.sensor_desc': 'Water level sensors will auto-detect flood conditions. No manual trigger needed — LoRaWAN sensors report in real-time.',
    'bencana.evacuation': 'Evacuation',
    'bencana.volunteer': 'Volunteer',
    'bencana.cleanup': 'Post-flood Cleanup Network',
    'bencana.request_help': 'Request Help',
    'bencana.no_requests': 'No open requests. All clear!',
    'bencana.accept': 'ACCEPT',
    'bencana.secured': 'SECURED',
    'bencana.cancel': 'CANCEL',
    'bencana.cancel_confirm': 'Are you sure you want to cancel this request?',
    'bencana.request_volunteers': 'Request Volunteers',
    'bencana.household': 'Household / Organization',
    'bencana.help_needed': 'Help Needed',
    'bencana.distance': 'Distance (approx)',
    'bencana.area': 'Area / Location',
    'bencana.submit_request': 'Submit Request',
    'bencana.ai_priority': 'AI Assigning Priority...',
    'bencana.active_route': 'Active Route',
    'bencana.standby': 'Standby',
    'bencana.map_info': 'Live GPS mapping active.',
    'bencana.priority': 'Priority',
  },
  zh: {
    'greeting.morning': '早上好！☀️',
    'greeting.noon': '午安 🌤️',
    'greeting.evening': '傍晚好 🌅',
    'greeting.night': '晚安 🌙',
    'greeting.latenight': '夜猫子？🦉',
    'header.notifications': '通知',
    'header.no_notif': '暂无通知',
    'header.notif_hint': '活动提醒将在此显示',
    'menu.profile': '我的个人资料',
    'menu.language': '语言',
    'menu.signout': '退出登录',
    'loading': '加载NADI中...',
    'levelup': '升级！🎉',
    'levelup.desc': '您现在是等级',
    'nav.nadipass': 'Nadi卡',
    'nav.infra': '基础设施',
    'nav.voice': '声音',
    'nav.bencana': '灾害',
    'nav.niaga': '贸易',
    'niaga.title': 'Nadi-贸易',
    'niaga.subtitle': '超本地B2B供应链',
    'niaga.active_listings': '活跃列表',
    'niaga.listings': '个列表',
    'niaga.connects': 'NADI将本地生产者直接连接到零售商。2%认证B2B匹配费。',
    'niaga.search': '搜索本地供应（如"石甲鱼"、"大米"）...',
    'niaga.live_log': '实时供应日志',
    'niaga.new': '新 ↑',
    'niaga.no_match': '未找到匹配的供应。',
    'niaga.no_listings': '暂无列表。成为第一个发布者！',
    'niaga.acquire': '获取',
    'niaga.post': '发布',
    'niaga.post_supply': '发布供应',
    'niaga.seller': '卖家',
    'niaga.item': '商品',
    'niaga.price': '价格',
    'niaga.location': '地点',
    'niaga.category': '类别',
    'niaga.post_listing': '发布列表',
    'niaga.ai_verifying': 'AI验证中...',
    'bencana.title': 'NADI 灾害',
    'bencana.subtitle': '动态危机与洪水路线',
    'bencana.lorawan': 'LoRaWAN声纳',
    'bencana.sensor_safe': '1级：安全',
    'bencana.sensor_warning': '2级：警告',
    'bencana.sensor_danger': '3级：危险',
    'bencana.sensor_desc': '水位传感器将自动检测洪水状况。无需手动触发——LoRaWAN传感器实时报告。',
    'bencana.evacuation': '疏散',
    'bencana.volunteer': '志愿者',
    'bencana.cleanup': '洪后清理网络',
    'bencana.request_help': '请求帮助',
    'bencana.no_requests': '没有未处理的请求。一切正常！',
    'bencana.accept': '接受',
    'bencana.secured': '已确保',
    'bencana.cancel': '取消',
    'bencana.cancel_confirm': '确定要取消此请求吗？',
    'bencana.request_volunteers': '请求志愿者',
    'bencana.household': '家庭/组织',
    'bencana.help_needed': '需要的帮助',
    'bencana.distance': '距离（大约）',
    'bencana.area': '区域/地点',
    'bencana.submit_request': '提交请求',
    'bencana.ai_priority': 'AI分配优先级...',
    'bencana.active_route': '活跃路线',
    'bencana.standby': '待命',
    'bencana.map_info': '实时GPS地图已激活。',
    'bencana.priority': '优先级',
  },
  ta: {
    'greeting.morning': 'காலை வணக்கம்! ☀️',
    'greeting.noon': 'மதிய வணக்கம் 🌤️',
    'greeting.evening': 'மாலை வணக்கம் 🌅',
    'greeting.night': 'இரவு வணக்கம் 🌙',
    'greeting.latenight': 'இரவு ஆந்தையா? 🦉',
    'header.notifications': 'அறிவிப்புகள்',
    'header.no_notif': 'இன்னும் அறிவிப்புகள் இல்லை',
    'header.notif_hint': 'செயல்பாட்டு எச்சரிக்கைகள் இங்கே தோன்றும்',
    'menu.profile': 'எனது சுயவிவரம்',
    'menu.language': 'மொழி',
    'menu.signout': 'வெளியேறு',
    'loading': 'NADI ஏற்றுகிறது...',
    'levelup': 'நிலை உயர்வு! 🎉',
    'levelup.desc': 'நீங்கள் இப்போது நிலை',
    'nav.nadipass': 'Nadi-பாஸ்',
    'nav.infra': 'உள்கட்டமைப்பு',
    'nav.voice': 'குரல்',
    'nav.bencana': 'பேரிடர்',
    'nav.niaga': 'வணிகம்',
    'niaga.title': 'Nadi-வணிகம்',
    'niaga.subtitle': 'உள்ளூர் B2B விநியோகச் சங்கிலி',
    'niaga.active_listings': 'செயலில் உள்ள பட்டியல்கள்',
    'niaga.listings': 'பட்டியல்கள்',
    'niaga.connects': 'NADI உள்ளூர் உற்பத்தியாளர்களை நேரடியாக சில்லறை விற்பனையாளர்களுடன் இணைக்கிறது.',
    'niaga.search': 'உள்ளூர் வழங்கலைத் தேடுங்கள்...',
    'niaga.live_log': 'நேரடி வழங்கல் பதிவு',
    'niaga.new': 'புதியது ↑',
    'niaga.no_match': 'பொருத்தமான வழங்கல் இல்லை.',
    'niaga.no_listings': 'இன்னும் பட்டியல்கள் இல்லை. முதலில் பதிவிடுங்கள்!',
    'niaga.acquire': 'பெறுக',
    'niaga.post': 'பதிவிடு',
    'niaga.post_supply': 'வழங்கலைப் பதிவிடு',
    'niaga.seller': 'விற்பனையாளர்',
    'niaga.item': 'பொருள்',
    'niaga.price': 'விலை',
    'niaga.location': 'இடம்',
    'niaga.category': 'வகை',
    'niaga.post_listing': 'பட்டியலைப் பதிவிடு',
    'niaga.ai_verifying': 'AI சரிபார்க்கிறது...',
    'bencana.title': 'NADI பேரிடர்',
    'bencana.subtitle': 'மாறும் நெருக்கடி & வெள்ள வழி',
    'bencana.lorawan': 'LoRaWAN சோனார்',
    'bencana.sensor_safe': 'நிலை 1: பாதுகாப்பு',
    'bencana.sensor_warning': 'நிலை 2: எச்சரிக்கை',
    'bencana.sensor_danger': 'நிலை 3: ஆபத்து',
    'bencana.sensor_desc': 'நீர்மட்ட உணரிகள் வெள்ள நிலைமைகளை தானாக கண்டறியும்.',
    'bencana.evacuation': 'வெளியேற்றம்',
    'bencana.volunteer': 'தன்னார்வலர்',
    'bencana.cleanup': 'வெள்ளத்திற்குப் பிந்தைய சுத்திகரிப்பு',
    'bencana.request_help': 'உதவி கேள்',
    'bencana.no_requests': 'திறந்த கோரிக்கைகள் இல்லை. அனைத்தும் சரி!',
    'bencana.accept': 'ஏற்கவும்',
    'bencana.secured': 'பாதுகாக்கப்பட்டது',
    'bencana.cancel': 'ரத்து',
    'bencana.cancel_confirm': 'இந்தக் கோரிக்கையை ரத்து செய்ய விரும்புகிறீர்களா?',
    'bencana.request_volunteers': 'தன்னார்வலர்களைக் கோரு',
    'bencana.household': 'குடும்பம் / அமைப்பு',
    'bencana.help_needed': 'தேவையான உதவி',
    'bencana.distance': 'தூரம் (தோராயம்)',
    'bencana.area': 'பகுதி / இடம்',
    'bencana.submit_request': 'கோரிக்கையை சமர்ப்பி',
    'bencana.ai_priority': 'AI முன்னுரிமை அமைக்கிறது...',
    'bencana.active_route': 'செயலில் வழி',
    'bencana.standby': 'தயார்நிலை',
    'bencana.map_info': 'நேரடி GPS வரைபடம் செயலில்.',
    'bencana.priority': 'முன்னுரிமை',
  },
  ar: {
    'greeting.morning': 'صباح الخير! ☀️',
    'greeting.noon': 'مساء الخير 🌤️',
    'greeting.evening': 'مساء الخير 🌅',
    'greeting.night': 'مساء الخير 🌙',
    'greeting.latenight': 'بومة ليلية؟ 🦉',
    'header.notifications': 'الإشعارات',
    'header.no_notif': 'لا توجد إشعارات بعد',
    'header.notif_hint': 'ستظهر تنبيهات النشاط هنا',
    'menu.profile': 'ملفي الشخصي',
    'menu.language': 'اللغة',
    'menu.signout': 'تسجيل الخروج',
    'loading': 'جاري تحميل NADI...',
    'levelup': 'ترقية! 🎉',
    'levelup.desc': 'أنت الآن في المستوى',
    'nav.nadipass': 'بطاقة نادي',
    'nav.infra': 'البنية التحتية',
    'nav.voice': 'الصوت',
    'nav.bencana': 'الكوارث',
    'nav.niaga': 'التجارة',
    'niaga.title': 'نادي-التجارة',
    'niaga.subtitle': 'سلسلة التوريد المحلية B2B',
    'niaga.active_listings': 'القوائم النشطة',
    'niaga.listings': 'قائمة',
    'niaga.connects': 'NADI يربط المنتجين المحليين مباشرة بالتجار. رسوم مطابقة B2B 2%.',
    'niaga.search': 'ابحث في الإمدادات المحلية...',
    'niaga.live_log': 'سجل الإمداد المباشر',
    'niaga.new': 'جديد ↑',
    'niaga.no_match': 'لم يتم العثور على إمداد مطابق.',
    'niaga.no_listings': 'لا توجد قوائم بعد. كن أول من ينشر!',
    'niaga.acquire': 'احصل',
    'niaga.post': 'نشر',
    'niaga.post_supply': 'نشر الإمداد',
    'niaga.seller': 'البائع',
    'niaga.item': 'المنتج',
    'niaga.price': 'السعر',
    'niaga.location': 'الموقع',
    'niaga.category': 'الفئة',
    'niaga.post_listing': 'نشر القائمة',
    'niaga.ai_verifying': 'AI يتحقق...',
    'bencana.title': 'NADI الكوارث',
    'bencana.subtitle': 'مسار الأزمات والفيضانات الديناميكي',
    'bencana.lorawan': 'سونار LoRaWAN',
    'bencana.sensor_safe': 'المستوى 1: آمن',
    'bencana.sensor_warning': 'المستوى 2: تحذير',
    'bencana.sensor_danger': 'المستوى 3: خطر',
    'bencana.sensor_desc': 'ستكتشف مستشعرات مستوى المياه ظروف الفيضان تلقائيًا.',
    'bencana.evacuation': 'الإخلاء',
    'bencana.volunteer': 'المتطوعون',
    'bencana.cleanup': 'شبكة تنظيف ما بعد الفيضان',
    'bencana.request_help': 'طلب مساعدة',
    'bencana.no_requests': 'لا توجد طلبات مفتوحة. الوضع آمن!',
    'bencana.accept': 'قبول',
    'bencana.secured': 'مؤمّن',
    'bencana.cancel': 'إلغاء',
    'bencana.cancel_confirm': 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟',
    'bencana.request_volunteers': 'طلب متطوعين',
    'bencana.household': 'الأسرة / المنظمة',
    'bencana.help_needed': 'المساعدة المطلوبة',
    'bencana.distance': 'المسافة (تقريبًا)',
    'bencana.area': 'المنطقة / الموقع',
    'bencana.submit_request': 'إرسال الطلب',
    'bencana.ai_priority': 'AI يحدد الأولوية...',
    'bencana.active_route': 'المسار النشط',
    'bencana.standby': 'استعداد',
    'bencana.map_info': 'خريطة GPS مباشرة نشطة.',
    'bencana.priority': 'الأولوية',
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'ms',
  setLang: () => { },
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('ms');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('nadi_lang') as LangCode | null;
      if (saved && translations[saved]) setLangState(saved);
    } catch { /* ignore */ }
  }, []);

  const setLang = (code: LangCode) => {
    setLangState(code);
    try { localStorage.setItem('nadi_lang', code); } catch { /* ignore */ }
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
